# Data Source Properties
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/web2
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update



# Disable the default loggers



# Show SQL executed with parameter bindings
#logging.level.org.hibernate.SQL = DEBUG
#logging.level.org.hibernate.type.descriptor = TRACE

# Elastic Kibana
logging:
  file:
    path: D:\\ElasticSearch\\
  level:
    root: warn
    org.springframework: INFO
    org: WARN
    blog: WARN

app:
  default:
    password: 1234

redis:
  host: localhost
  port: 6379

upload_users:
  path: C:/Users/PC/IdeaProjects/laba_web2/src/main/java/ru/web/laba_web2/uploads_users

upload_offers:
  path: C:/Users/PC/IdeaProjects/laba_web2/src/main/java/ru/web/laba_web2/uploads_offers

